package com.simplon.nooky.project.entities;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

@MappedSuperclass
public class EntityAbstract {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	private Long id;
	
	public EntityAbstract() {
	}
	
	public Long getId() {
		return this.id;
	}
	
	private void setId(Long id) {
		// id generated by database
		this.id = id;
	}
}