INSERT INTO addresses (road, zip_code, city) VALUES
('1 Rue de la Mode', '75001', 'Paris'),
('5 Avenue du Style', '69001', 'Lyon'),
('10 Rue de la Chaussure', '33000', 'Bordeaux'),
('15 Avenue de la Mode', '75002', 'Paris'),
('20 Rue du Chic', '44000', 'Nantes'),
('25 Boulevard de la Tendance', '13001', 'Marseille'),
('30 Avenue du Style', '69002', 'Lyon'),
('35 Rue de la Mode', '59000', 'Lille'),
('40 Boulevard du Fashion', '75002', 'Paris'),
('45 Rue de la Chaussure', '33001', 'Bordeaux');

INSERT INTO users (email, password, username, firstname, lastname, description, picture, created_at, address_id) VALUES
('user1@example.com', '$2a$12$WKxz27iChcbPj8uJUeFXpeh7alLYMrXMRUErQkgHlwZEb3rEQC5Xa', 'JeanTrendy', 'Jean', 'Dupont', 'Passionné de mode, apprécie particulièrement les pièces vintage des années 60 et 70', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuJ_pIKPGu7EUrrRmeKvAKlBDBjF6oUDSoYDHAS0DRGQ&s', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '10 Rue de la Chaussure' AND zip_code = '33000' AND city = 'Bordeaux')),
('user2@example.com', '$2a$12$gUxCdCHIrmierqlXqqZJGucaG67w7cCMsBRG64G83z38sCx9kOsya', 'MarieFashion', 'Marie', 'Dubois', 'Je déniche régulièrement des pépites dans les fripperies de la ville de Lyon et recherche accessoires originaux', 'https://st2.depositphotos.com/38340270/49057/i/450/depositphotos_490576070-stock-photo-young-woman-beautiful-siberian-husky.jpg', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '5 Avenue du Style' AND zip_code = '69001' AND city = 'Lyon')),
('user3@example.com', '$2a$12$PjCkYMnJwewts1F3pC365ODrmjRQcJtEUCEQWUPJIOqZJJGqdiUJe', 'Pierrot', 'Pierre', 'Durand', 'Aime la mode pratique et fonctionnelle type vêtements de sport ou de travail', 'https://media.vogue.fr/photos/60d481e8ff53804c0281f81d/4:3/w_1999,h_1499,c_limit/Paris%20Mens%20SS22%20day%202%20by%20STYLEDUMONDE%20Street%20Style%20Fashion%20Photography_95A4787FullRes.jpg', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '10 Rue de la Chaussure' AND zip_code = '33000' AND city = 'Bordeaux')),
('user4@example.com', '$2a$12$l.nNuzWJyqpWjnueiO29NuJDB/dT0BHdWYAFUYasM3SK9DIZ53bEu', 'Nath4', 'Nathalie', 'Durand', 'Pétillante, je suis fan de vêtements colorés type mode espagnole', 'https://img.lemde.fr/2024/03/04/0/0/3000/2830/664/0/75/0/d85f37a_1709546753207-alexander-mcqueen-rtw-aw24-look-25.jpg', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '10 Rue de la Chaussure' AND zip_code = '33000' AND city = 'Bordeaux')),
('user5@example.com', '$2a$12$rqP2GuEN9fxclv5ayU99I.6YVAXd8SVWzgE0a.Fp2q/n5Z2/luUSq', 'TomThomas', 'Thomas', 'Martin', 'Citadin un peu dandy, je préfère les vêtements de qualité. Pas de fast-fashion pour moi.', 'https://leblogdemonsieur.com/wp-content/uploads/2016/07/blog-mode-homme-leblogdemonsieur-nickwooster-look-homme-noir-2-e1469803043929.jpg', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '15 Avenue de la Mode' AND zip_code = '75002' AND city = 'Paris')),
('user6@example.com', '$2a$12$ocEgAyyJGXR5Y2oO8D67VOnXOQ4MZtO5qf2YiPJSY7HQUcpKnk4UW', 'SophMode', 'Sophie', 'Lefèvre', 'Maman débordée, je cherche des vêtements pratiques et confortables pour enfants et adultes.', 'https://cdn.monsieurtshirt.com/images/36845/product_large/t-shirt-femme-maman-epuisee---cadeaux-papa-cadeaux-maman.jpg?1627898500000&additionalExtensions=WEBP&additionalExtensions=AVIF', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '20 Rue du Chic' AND zip_code = '44000' AND city = 'Nantes')),
('user7@example.com', '$2a$12$sdy63CFVnbLWuISDjAkIEOTmFE1tOChbkHRNdMCnabkqlB0KO.XKG', 'Toinou', 'Antoine', 'Leroy', 'Marseillais randonneur, je recherche des vêtements de sports', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS6yVTV2rOa_Kh_pZmJAVeyZXX_nc6MhB46e7OOjNTqg&s', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '25 Boulevard de la Tendance' AND zip_code = '13001' AND city = 'Marseille')),
('user8@example.com', '$2a$12$Bp8exdU1ZMPJABAq4Tl6k.MEGcH.eCp7FKw7H44J0O9YM7nOEoXa.', 'EmilieEmo', 'Émilie', 'Roux', 'Chaussures, chaussures, chaussures, en taille 38 !!! Fan de chaussures ! Sinon, accessoires, tenues classes, etc.', 'https://www.bibamagazine.fr/wp-content/uploads/biba/2022/09/envie_de_fraise_vetements_grossesse.jpg', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '30 Avenue du Style' AND zip_code = '69002' AND city = 'Lyon')),
('user9@example.com', '$2a$12$nNT0RZnDbblTySC2P6EcruCddVa2EtEtwpuqlDQ/GVhE3NEqfDMN6', 'LucasLeChti', 'Lucas', 'Garcia', 'Addict à la marque Le Coq Sportif et aux sneakers, je souhaite exclusivement échanger les produits de mon vestiaire contre des vêtements de cette marque ou des sneakers neuves (toutes marques confondues).','https://www.cdiscount.com/pdt2/5/2/6/3/700x700/mp97279526/rw/sweat-le-coq-sportif-homme-le-coq-sportif-auth.jpg', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '35 Rue de la Mode' AND zip_code = '59000' AND city = 'Lille')),
('user10@example.com', '$2a$12$bEt9b6iPMkGud7dp6Z.q/eMDjhode/67Dkz/jzxu0zcXGVwtOiGmC', 'ManonParis', 'Manon', 'Moreau', 'Je souhaite des vêtements de bonne qualité, élégants. Parisienne, jusque dans le dressing.', 'https://maiaetzoe.com/wp-content/uploads/2020/11/Robe-pull-noire-femme-maman-imparfaite-3.jpg', CURRENT_TIMESTAMP,
    (SELECT id FROM addresses WHERE road = '40 Boulevard du Fashion' AND zip_code = '75002' AND city = 'Paris'));

INSERT INTO products (reference, name, description, picture, added_at, wishlist, category_id, size_id, type_id, user_id) VALUES
('PROD001', 'T-Shirt Noir', 'T-Shirt noir basique', 'https://vision-naire.com/cdn/shop/products/2-Tshirt-visionnaire-TCPR-noir_2500x.jpg?v=1658161284', CURRENT_TIMESTAMP, 'Accessoire sympa ou t-shirt rock',
    (SELECT id FROM categories WHERE reference = 'CAT003'),
    (SELECT id FROM sizes WHERE reference = 'SIZ003'),
    (SELECT id FROM types WHERE reference = 'TYP035'),
    (SELECT id FROM users WHERE email = 'user1@example.com')),
('PROD002', 'Chemise à carreaux', 'Chemise à carreaux rouge et bleue, tissus de qualité', 'https://www.cottonsociety.com/173158-thickbox_default/chemise-homme-gratte-carreaux-rouge-et-bleu.jpg', CURRENT_TIMESTAMP, 'Veste noire en taille 40, pantalon noir en taille 40 ou chemises hommes en taille L',
    (SELECT id FROM categories WHERE reference = 'CAT003'),
    (SELECT id FROM sizes WHERE reference = 'SIZ002'),
    (SELECT id FROM types WHERE reference = 'TYP014'),
    (SELECT id FROM users WHERE email = 'user3@example.com')),
('PROD003', 'Baskets Blanches', 'Baskets blanches à lacets', 'https://www.pasdegeant.fr/media/catalog/product/cache/e3613eb285f3e2ba1ac505df7b0eeec2/b/a/baskets-blanche-5_1.jpg', CURRENT_TIMESTAMP, 'Chapeaux de tous types, vêtements femme taille M',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ025'),
    (SELECT id FROM types WHERE reference = 'TYP034'),
    (SELECT id FROM users WHERE email = 'user2@example.com')),
('PROD004', 'Montre en cuir', 'Montre-bracelet en cuir marron', 'https://charlie-paris.com/cdn/shop/products/bracelet-cuir-mick-terracotta-bracelet-charlie-watch-acier-5.jpg?v=1687263999&width=950', CURRENT_TIMESTAMP, 'Chaussures en taille 38',
    (SELECT id FROM categories WHERE reference = 'CAT004'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP003'),
    (SELECT id FROM users WHERE email = 'user4@example.com')),
('PROD005', 'Robe été à fleurs', 'Robe légère avec motif floral pour été', 'https://www.esprit.fr/dw/image/v2/BDSS_PRD/on/demandware.static/-/Sites-esprit-master/default/dw77514240/images/20/043/043EE1E323_873_20.jpg?sfrm=jpg&sw=700&sh=1050&sm=fit', CURRENT_TIMESTAMP, 'Sandales en taille 38',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ003'),
    (SELECT id FROM types WHERE reference = 'TYP028'),
    (SELECT id FROM users WHERE email = 'user4@example.com')),
('PROD006', 'Sac à dos vintage', 'Sac à dos en toile avec un style vintage', 'https://eziclic.com/cdn/shop/products/sac-a-dos-vintage-everest-7_600x600.jpg', CURRENT_TIMESTAMP, 'Jupes en taille M',
    (SELECT id FROM categories WHERE reference = 'CAT004'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP032'),
    (SELECT id FROM users WHERE email = 'user6@example.com')),
('PROD007', 'Lunettes de soleil aviateur', 'Lunettes de soleil aviateur classiques', 'https://lumeos.fr/wp-content/uploads/2022/02/0-eac8de.jpeg', CURRENT_TIMESTAMP, 'Pulls en laine en taille S',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP025'),
    (SELECT id FROM users WHERE email = 'user6@example.com')),
('PROD008', 'Blouson en cuir noir', 'Blouson en cuir noir style motard', 'https://www.cuiravenue.com/1795-large_default/blouson-cuir-homme-noir-best-one.jpg', CURRENT_TIMESTAMP, 'Chemises à carreaux en taille XL',
    (SELECT id FROM categories WHERE reference = 'CAT003'),
    (SELECT id FROM sizes WHERE reference = 'SIZ006'),
    (SELECT id FROM types WHERE reference = 'TYP005'),
    (SELECT id FROM users WHERE email = 'user5@example.com')),
('PROD009', 'Parapluie transparent', 'Parapluie transparent avec une poignée en forme de canard', 'https://www.parapluie-de-france.com/images/articles/1894/538441018128.jpg', CURRENT_TIMESTAMP, 'Bottes de pluie en taille 37',
    (SELECT id FROM categories WHERE reference = 'CAT004'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP038'),
    (SELECT id FROM users WHERE email = 'user2@example.com')),
('PROD010', 'Boucles pendantes', 'Boucles pendantes avec des perles', 'https://static.wixstatic.com/media/c5e788_0fc4b32eb94e4b029bca0f906da81af4~mv2.jpg/v1/fill/w_560,h_996,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/c5e788_0fc4b32eb94e4b029bca0f906da81af4~mv2.jpg', CURRENT_TIMESTAMP, 'Bijoux ou accessoires classes et sympas',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP003'),
    (SELECT id FROM users WHERE email = 'user10@example.com')),
('PROD011', 'Mocassins en daim', 'Mocassins en daim beige', 'https://www.elorell.com/17635-large_default/mocassins-homme-en-daim.jpg', CURRENT_TIMESTAMP, 'Produits de la marque Le Coq Sportif ou sneakers de qualité en taille 42',
    (SELECT id FROM categories WHERE reference = 'CAT003'),
    (SELECT id FROM sizes WHERE reference = 'SIZ034'),
    (SELECT id FROM types WHERE reference = 'TYP029'),
    (SELECT id FROM users WHERE email = 'user9@example.com')),
('PROD012', 'Ensemble de bagages', 'Ensemble de bagages en polycarbonate', 'https://m.media-amazon.com/images/I/71G0Lr5LQOL._AC_UY1000_.jpg', CURRENT_TIMESTAMP, 'Manteaux en laine en taille M',
    (SELECT id FROM categories WHERE reference = 'CAT004'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP032'),
    (SELECT id FROM users WHERE email = 'user1@example.com')),
('PROD013', 'Bague en argent', 'Bague en argent avec une pierre turquoise', 'https://www.amazonia-bijoux.fr/85-large_default/bague-amazonia-xpuchina-turquoise-310ct-et-argent-massif.jpg', CURRENT_TIMESTAMP, 'Foulards en soie',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP003'),
    (SELECT id FROM users WHERE email = 'user2@example.com')),
('PROD014', 'Sweat à capuche', 'Sweat à capuche gris chiné', 'https://www.boysdiffusion.com/28385-large/sweat-capuche-carhartt-ochredark-navy.jpg', CURRENT_TIMESTAMP, 'Baskets de sport en taille 42',
    (SELECT id FROM categories WHERE reference = 'CAT003'),
    (SELECT id FROM sizes WHERE reference = 'SIZ006'),
    (SELECT id FROM types WHERE reference = 'TYP031'),
    (SELECT id FROM users WHERE email = 'user9@example.com')),
('PROD015', 'Escarpins', 'Escarpins noirs talons 8 centimètres', 'https://www.modress.com/ori-escarpins-noirs-vernis-effet-croco-14054.jpg', CURRENT_TIMESTAMP, 'Pièces originales, bijoux, chaussures, vêtements',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ028'),
    (SELECT id FROM types WHERE reference = 'TYP033'),
    (SELECT id FROM users WHERE email = 'user10@example.com')),
('PROD016', 'Chemise classique', 'Chemise blanche cintrée, état neuf', 'https://media.lamaisonduteeshirt.com/eXJ6oePfaD6uh_wd7ARFLw9ZIzv1oddcXDjEjmjx-zQ/pr:580x580/aHR0cDovL21lZGlhMi5kZXNpZ25wYXJ0bmVyLmZyL2MvcC80NTMzLzQ1MzMtMTY5NS0xLmpwZw?v=1610018813', CURRENT_TIMESTAMP, 'T-shirts imprimés ou robes été en taille 38',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ003'),
    (SELECT id FROM types WHERE reference = 'TYP014'),
    (SELECT id FROM users WHERE email = 'user2@example.com')),
('PROD017', 'Casquette', 'Casquette américaine de type baseball couleur bleue', 'https://assets.laboutiqueofficielle.com/w_450,q_auto,f_auto/media/products/2016/07/28/new-era_81016_11157579_NOOSSS19_20190529T113912_01.jpg', CURRENT_TIMESTAMP, 'Chaussures de sport en taille 40 ou vêtements de sports pour femmes en taille 38-40',
    (SELECT id FROM categories WHERE reference = 'CAT003'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP010'),
    (SELECT id FROM users WHERE email = 'user7@example.com')),
('PROD018', 'Pantalon de tailleur', 'Pantalon à pinces de couleur noire', 'https://www.melleboutique-toulouse.fr/11333-thickbox_default/pantalon-tailleur-classique-a-pinces-noir-hippocampe-melle-boutique.jpg', CURRENT_TIMESTAMP, 'Robe été en taille 36-38 ou chaussures en taille 38',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ004'),
    (SELECT id FROM types WHERE reference = 'TYP030'),
    (SELECT id FROM users WHERE email = 'user8@example.com')),
('PROD019', 'Lot de barrettes', 'Lot de barrettes, jamais utilisées', 'https://dolce-perla.com/wp-content/uploads/2023/08/lot-3-barrettes-tons-camel-scaled.jpg.webp', CURRENT_TIMESTAMP, 'Accessoires de tous types',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ040'),
    (SELECT id FROM types WHERE reference = 'TYP003'),
    (SELECT id FROM users WHERE email = 'user10@example.com')),
('PROD020', 'Jupe à fleurs', 'Jupe à fleurs beaucoup utilisées mais bon état', 'https://www.cdiscount.com/pdt2/3/7/9/1/700x700/mp55256379/rw/jupe-a-fleurs-ample-decontractee-pour-femmes-jupe.jpg', CURRENT_TIMESTAMP, 'Jupe courte ou longue, unie, noire blanche ou colorée en taille 38',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ005'),
    (SELECT id FROM types WHERE reference = 'TYP023'),
    (SELECT id FROM users WHERE email = 'user4@example.com')),
('PROD021', 'Lot de t-shirts', 'Lot de t-shirts de couleurs différentes, bon état', 'https://static.kiabi.com/images/lot-de-3-t-shirts-a-col-rond-beige-zb636_1_frb1.jpg', CURRENT_TIMESTAMP, 'Tenue élégante type robe ou combinaison, en taille 38',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ004'),
    (SELECT id FROM types WHERE reference = 'TYP035'),
    (SELECT id FROM users WHERE email = 'user4@example.com')),
('PROD022', 'Babies fille', 'Babies fille couleur bleue, très peu portées', 'https://www.minishoes.fr/7329-large_default/babies-fille-cuir-boucle.jpg', CURRENT_TIMESTAMP, 'Vêtements enfants pour fille, taille 8 à 12 ans',
    (SELECT id FROM categories WHERE reference = 'CAT001'),
    (SELECT id FROM sizes WHERE reference = 'SIZ010'),
    (SELECT id FROM types WHERE reference = 'TYP013'),
    (SELECT id FROM users WHERE email = 'user6@example.com')),
('PROD023', 'Sandales roses', 'Sandales roses', 'https://cdn1.jolicloset.com/img4/full/2023/05/873099-2.jpg', CURRENT_TIMESTAMP, 'Bottes en cuir vintage taille 38',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ027'),
    (SELECT id FROM types WHERE reference = 'TYP033'),
    (SELECT id FROM users WHERE email = 'user6@example.com')),
('PROD024', 'Combinaison', 'Combinaison habillée de type tenue de soirée', 'https://chroniquebordelaise.com/wp-content/uploads/2016/12/Look-de-f%C3%AAtes-combinaison-noire-mango-dentelle-15.jpg', CURRENT_TIMESTAMP, 'Sacs à main en cuir ou daim',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ004'),
    (SELECT id FROM types WHERE reference = 'TYP018'),
    (SELECT id FROM users WHERE email = 'user10@example.com')),
('PROD025', 'Chaussettes', 'Chaussettes husky neuves', 'https://m.media-amazon.com/images/I/81W7ZTKuX9L._AC_UY1000_.jpg', CURRENT_TIMESTAMP, 'Accessoires',
    (SELECT id FROM categories WHERE reference = 'CAT002'),
    (SELECT id FROM sizes WHERE reference = 'SIZ027'),
    (SELECT id FROM types WHERE reference = 'TYP038'),
    (SELECT id FROM users WHERE email = 'user10@example.com'));

INSERT INTO exchanges (product_offered_id, product_exchanged_id, owner_id, exchanger_id, status_id) VALUES
    ((SELECT id FROM products WHERE reference = 'PROD001'), (SELECT id FROM products WHERE reference = 'PROD002'), (SELECT id FROM users WHERE email = 'user1@example.com'), (SELECT id FROM users WHERE email = 'user2@example.com'), (SELECT id FROM status WHERE code = 'COD1')),
    ((SELECT id FROM products WHERE reference = 'PROD003'), (SELECT id FROM products WHERE reference = 'PROD004'), (SELECT id FROM users WHERE email = 'user1@example.com'), (SELECT id FROM users WHERE email = 'user3@example.com'), (SELECT id FROM status WHERE code = 'COD5')),
    ((SELECT id FROM products WHERE reference = 'PROD005'), (SELECT id FROM products WHERE reference = 'PROD006'), (SELECT id FROM users WHERE email = 'user2@example.com'), (SELECT id FROM users WHERE email = 'user3@example.com'), (SELECT id FROM status WHERE code = 'COD2'));